fix: Deny access should land to the home page
trustbloc/edge-sandbox pull request #597
Opened 2020-10-08 19:10 UTC by serenahacker

closes #349

Signed-off-by: serenahacker <serenahacker@gmail.com>

2020-10-13 15:09 UTC, talwinder50 approved these changes

2020-10-13 20:07 UTC, rolsonquadras requested changes

2020-10-13 20:07 UTC, rolsonquadras commented on cmd/login-consent-server/main.go
> +	http.Redirect(w, req, "https://issuer.trustbloc.local/", http.StatusFound)
We shouldn't hardcode the url (this is a local deployment specific url).

2020-10-14 19:44 UTC, rolsonquadras approved these changes

2020-10-15 16:56 UTC, merged