chore: update edge-service and edv image tag
trustbloc/edge-sandbox pull request #609
Opened 2020-10-19 14:36 UTC by grace0925

Signed-off-by: Grace Liu <grace.liu@securekey.com>

2020-10-19 14:44 UTC, rolsonquadras approved these changes

2020-10-19 14:44 UTC, sandrask approved these changes

2020-10-19 14:48 UTC, fqutishat requested changes
did you run the demo

2020-10-23 18:10 UTC, grace0925 commented
> did you run the demo

I ran through new bank account usecase, and vc playground.
It works except I couldn't complete the vc flow because the rp site gives 404

2020-10-23 18:37 UTC, rolsonquadras commented
> > did you run the demo
> > @fqutishat
> > I ran through new bank account usecase, and vc playground.
> > It works except I couldn't complete the vc flow because the rp site gives 404

@grace0925 The bank account demo is not using the edge-service code. We need to verify the flow through issuer and rp site ([vcs demo](https://github.com/trustbloc/edge-sandbox/blob/master/docs/demo/sandbox_vcs_playground.md)). 

@talwinder50 Can we please check the RP site giving 404 error ?

2020-10-27 15:32 UTC, rolsonquadras approved these changes

2020-10-27 15:33 UTC, fqutishat approved these changes

2020-10-27 15:34 UTC, merged